/* Per-game offsets, ported from the reference editor's helper classes
 * (IEGOHelper / IEGOCSHelper / IEGOGalaxyHelper). See NOTES.md. */
#include "app.h"

const GameDef GAMES[] = {
    {
        .name = "GO Galaxy", .shortname = "galaxy", .magic = 0x40F1,
        .time_off = 0x20, .name_off = 0x3C, .team_off = 0x5C,
        .money_off = 0x268D0, .has_friendship = false, .coin_off = 0x26CC8,
        .chapter_off = 0x9F1C,
        .link_kind = LINK_LEVEL, .link_off = 0x90B4,
        .pdata_off = 0xF83C, .pindex_off = 0x26E28, .pmax = 336, .pblock = 268,
        .p_id_off = 8, .p_gp_off = 28, .p_invest_off = 52,
        .p_moves_off = 96,
        .db = GALAXY_DB, .db_count = GALAXY_DB_COUNT,
        .g1_off = 0xA394, .g1_n = 608, .g2_off = 0xC020, .g2_n = 452, .g3_off = 0xDC6C, .g3_n = 888,
        .idb = GALAXY_IDB, .idb_count = GALAXY_IDB_COUNT,
        .p_avatar_off = 68, .totem_off = 1, .records_off = 0x8FEB, .records_n = 17,
        .mdb = GALAXY_MDB, .mdb_count = GALAXY_MDB_COUNT, .adb = GALAXY_ADB, .adb_count = GALAXY_ADB_COUNT,
        .t_info = 0x26914, .t_info_str = 0x34, .t_name = 0x26B50, .t_name_str = 0x20, .t_players = 0x273A8, .t_count = 10,
        .unlock = UNLOCK_GALAXY, .unlock_n = UNLOCK_GALAXY_N, .unlock_end = UNLOCK_GALAXY_END,
        .unlock_label = "Unlock data DL + QR + GO/CS link",
    },
    {
        .name = "GO Chrono Stones (EU)", .shortname = "cs-eu", .magic = 0x4CF1,
        .time_off = 0x20, .name_off = 0x3C, .team_off = 0x64,
        .money_off = 0x1C0B0, .has_friendship = true, .coin_off = 0,
        .chapter_off = 0x10FC,
        .link_kind = LINK_LEVEL, .link_off = 0x3B4,
        .pdata_off = 0x5B1C, .pindex_off = 0x1C4E0, .pmax = 336, .pblock = 260,
        .p_id_off = 4, .p_gp_off = 12, .p_invest_off = 44,
        .p_moves_off = 88,
        .db = CS_DB, .db_count = CS_DB_COUNT,
        .g1_off = 0x14F4, .g1_n = 512, .g2_off = 0x2D00, .g2_n = 336, .g3_off = 0x420C, .g3_n = 800,
        .idb = CS_IDB, .idb_count = CS_IDB_COUNT,
        .p_avatar_off = 60, .records_off = 0x2EC, .records_n = 10,
        .mdb = CS_MDB, .mdb_count = CS_MDB_COUNT, .adb = CS_ADB, .adb_count = CS_ADB_COUNT,
        .t_info = 0x1C0F4, .t_info_str = 0x30, .t_name = 0x1C304, .t_name_str = 0x28, .t_players = 0x1CA60, .t_count = 10,
        .unlock = UNLOCK_CS_EU, .unlock_n = UNLOCK_CS_EU_N, .unlock_end = UNLOCK_CS_EU_END,
        .unlock_label = "Unlock data DL + password + GO link",
    },
    {
        .name = "GO Chrono Stones (JP)", .shortname = "cs-jp", .magic = 0xC4F1,
        .time_off = 0x20, .name_off = 0x3C, .team_off = 0x5C,
        .money_off = 0x1C060, .has_friendship = true, .coin_off = 0,
        .chapter_off = 0x10AC,
        .link_kind = LINK_LEVEL, .link_off = 0x364,
        .pdata_off = 0x5ACC, .pindex_off = 0x1C438, .pmax = 336, .pblock = 260,
        .p_id_off = 4, .p_gp_off = 12, .p_invest_off = 44,
        .p_moves_off = 88,
        .db = CS_DB, .db_count = CS_DB_COUNT,
        .g1_off = 0x14A4, .g1_n = 512, .g2_off = 0x2CB0, .g2_n = 336, .g3_off = 0x41BC, .g3_n = 800,
        .idb = CS_IDB, .idb_count = CS_IDB_COUNT,
        .p_avatar_off = 60, .records_off = 0x29C, .records_n = 10,
        .mdb = CS_MDB, .mdb_count = CS_MDB_COUNT, .adb = CS_ADB, .adb_count = CS_ADB_COUNT,
        .t_info = 0x1C0A4, .t_info_str = 0x30, .t_name = 0x1C2B4, .t_name_str = 0x20, .t_players = 0x1C9B8, .t_count = 10,
        .unlock = UNLOCK_CS_JP, .unlock_n = UNLOCK_CS_JP_N, .unlock_end = UNLOCK_CS_JP_END,
        .unlock_label = "Unlock data DL + password + GO link",
    },
    {
        .name = "GO (EU)", .shortname = "go-eu", .magic = 0x2CF1,
        .time_off = 0x24, .name_off = 0x3C, .team_off = 0x64,
        .money_off = 0x8DDC, .has_friendship = true, .coin_off = 0,
        .chapter_off = 0,
        .link_kind = LINK_GO_WORD, .link_off = 0x253,
        .pdata_off = 0x3488, .pindex_off = 0x8EC8, .pmax = 112, .pblock = 204,
        .p_id_off = 4, .p_gp_off = 12, .p_invest_off = 32,
        .p_moves_off = 76,
        .db = GO_DB, .db_count = GO_DB_COUNT,
        .g1_off = 0xA60, .g1_n = 256, .g2_off = 0x166C, .g2_n = 224, .g3_off = 0x2478, .g3_n = 512,
        .idb = GO_IDB, .idb_count = GO_IDB_COUNT,
        .p_avatar_off = 48,
        .mdb = GO_MDB, .mdb_count = GO_MDB_COUNT, .adb = GO_ADB, .adb_count = GO_ADB_COUNT,
        .t_info = 0x8E20, .t_info_str = 0x30, .t_players = 0x9088, .t_count = 3,
        .unlock = UNLOCK_GO_EU, .unlock_n = UNLOCK_GO_EU_N, .unlock_end = UNLOCK_GO_EU_END,
        .unlock_label = "Unlock data download",
    },
    {
        .name = "GO (JP)", .shortname = "go-jp", .magic = 0x6CF1,
        .time_off = 0x24, .name_off = 0x3C, .team_off = 0x5C,
        .money_off = 0x8D8C, .has_friendship = true, .coin_off = 0,
        .chapter_off = 0,
        .link_kind = LINK_GO_WORD, .link_off = 0x253,
        .pdata_off = 0x3438, .pindex_off = 0x8E78, .pmax = 112, .pblock = 204,
        .p_id_off = 4, .p_gp_off = 12, .p_invest_off = 32,
        .p_moves_off = 76,
        .db = GO_DB, .db_count = GO_DB_COUNT,
        .g1_off = 0xA10, .g1_n = 256, .g2_off = 0x161C, .g2_n = 224, .g3_off = 0x2428, .g3_n = 512,
        .idb = GO_IDB, .idb_count = GO_IDB_COUNT,
        .p_avatar_off = 48,
        .mdb = GO_MDB, .mdb_count = GO_MDB_COUNT, .adb = GO_ADB, .adb_count = GO_ADB_COUNT,
        .t_info = 0x8DD0, .t_info_str = 0x30, .t_players = 0x9038, .t_count = 3,
        .unlock = UNLOCK_GO_JP, .unlock_n = UNLOCK_GO_JP_N, .unlock_end = UNLOCK_GO_JP_END,
        .unlock_label = "Unlock data download",
    },
};

const int GAMES_N = sizeof(GAMES) / sizeof(*GAMES);
