#!/usr/bin/env python3
"""Generate 3ds/source/players_db.h from the reference editor's Galaxy player
dictionary (Players.cs). Names transliterated to ASCII for the 3DS console font."""

import re
import unicodedata

SRC = "reference/InazumaElevenSaveEditor/InazumaElevenSaveEditor/InazumaEleven/Common/GO/Players/Players.cs"
OUT = "3ds/source/players_db.h"

POS = {"Goalkeeper": "GK", "Defender": "DF", "Midfielder": "MF", "Forward": "FW"}
ELEM = {"Fire": "Fire", "Wind": "Wind", "Wood": "Wood", "Earth": "Erth"}


def ascii_name(s):
    s = unicodedata.normalize("NFKD", s)
    return "".join(c for c in s if ord(c) < 128)


src = open(SRC, encoding="utf-8").read()
galaxy = src[src.index("Galaxy = new Dictionary"):]
rows = []
seen = set()
for m in re.finditer(
    r'\{0x([0-9A-Fa-f]{8}),\s*new Player\s*\("([^"]*)",\s*(?:Position\.(\w+)\(\)|null),\s*(?:Element\.(\w+)\(\)|null)',
    galaxy,
):
    pid = int(m.group(1), 16)
    name = ascii_name(m.group(2))[:23]
    if pid == 0 or not name or pid in seen:
        continue
    seen.add(pid)
    rows.append((pid, POS.get(m.group(3), "??"), ELEM.get(m.group(4), "????"), name))

rows.sort()
with open(OUT, "w") as f:
    f.write("/* generated by tools/gen_players.py from Players.cs (Galaxy dict) */\n")
    f.write("#pragma once\n#include <stdint.h>\n\n")
    f.write("typedef struct { uint32_t id; char pos[3]; char elem[5]; char name[24]; } PlayerInfo;\n\n")
    f.write(f"#define PLAYERS_DB_COUNT {len(rows)}\n")
    f.write("static const PlayerInfo PLAYERS_DB[PLAYERS_DB_COUNT] = {\n")
    for pid, pos, elem, name in rows:
        esc = name.replace("\\", "").replace('"', "")
        f.write(f'    {{ 0x{pid:08X}, "{pos}", "{elem}", "{esc}" }},\n')
    f.write("};\n")
print(f"{len(rows)} players written to {OUT}")
