#!/usr/bin/env python3
"""Generate 3ds/source/items_db.h from the reference editor's item
dictionaries (Go / Cs / Galaxy). Names transliterated to ASCII."""

import re
import unicodedata

SRC = "reference/InazumaElevenSaveEditor/InazumaElevenSaveEditor/InazumaEleven/Common/GO/Items/Items.cs"
OUT = "3ds/source/items_db.h"

ENTRY = re.compile(r'\{0x([0-9A-Fa-f]{8}),\s*new Item\s*\("([^"]*)",\s*(\d+),\s*(\d+)')


def ascii_name(s):
    s = unicodedata.normalize("NFKD", s)
    s = "".join(c for c in s if ord(c) < 128)
    return s.replace("\\", "").replace('"', "")


def parse_dict(chunk):
    rows, seen = [], set()
    for m in ENTRY.finditer(chunk):
        iid = int(m.group(1), 16)
        name = ascii_name(m.group(2))[:27]
        sub = int(m.group(4))
        if iid == 0 or not name or iid in seen:
            continue
        seen.add(iid)
        rows.append((iid, sub, name))
    rows.sort()
    return rows


src = open(SRC, encoding="utf-8").read()
marks = {n: src.index(f"{n} = new Dictionary") for n in ("Go", "Cs", "Galaxy")}
bounds = sorted(marks.values()) + [len(src)]
with open(OUT, "w") as f:
    f.write("/* generated by tools/gen_items.py from Items.cs (Go/Cs/Galaxy dicts) */\n")
    f.write("#pragma once\n#include <stdint.h>\n\n")
    f.write("typedef struct { uint32_t id; uint8_t sub; char name[27]; } ItemInfo;\n\n")
    for n, s in marks.items():
        e = min(b for b in bounds if b > s)
        rows = parse_dict(src[s:e])
        up = n.upper()
        f.write(f"#define {up}_IDB_COUNT {len(rows)}\n")
        f.write(f"static const ItemInfo {up}_IDB[{up}_IDB_COUNT] = {{\n")
        for iid, sub, name in rows:
            f.write(f'    {{ 0x{iid:08X}, {sub}, "{name[:26]}" }},\n')
        f.write("};\n\n")
        print(n, len(rows))
