#!/usr/bin/env python3
"""Generate 3ds/source/moves_db.h and avatars_db.h from Moves.cs / Avatars.cs."""

import re
import unicodedata

BASE = "reference/InazumaElevenSaveEditor/InazumaElevenSaveEditor/InazumaEleven/Common/GO/"


def ascii_name(s):
    s = unicodedata.normalize("NFKD", s)
    s = "".join(c for c in s if ord(c) < 128)
    return s.replace("\\", "").replace('"', "")


def dict_chunks(src, names):
    marks = {n: src.index(f"{n} = new Dictionary") for n in names if f"{n} = new Dictionary" in src}
    bounds = sorted(marks.values()) + [len(src)]
    return {n: src[s:min(b for b in bounds if b > s)] for n, s in marks.items()}


# moves: independent dicts per game
src = open(BASE + "Moves/Moves.cs", encoding="utf-8").read()
MOVE = re.compile(r'\{0x([0-9A-Fa-f]{8}),\s*new Move\("([^"]*)",\s*(?:Element\.(\w+)\(\)|null),\s*(?:Position\.(\w+)\(\)|null)')
KIND = {"Shot": "SH", "Dribble": "DR", "Block": "BK", "Save": "SV", "Skill": "SK"}
with open("3ds/source/moves_db.h", "w") as f:
    f.write("/* generated by tools/gen_moves.py from Moves.cs */\n#pragma once\n#include <stdint.h>\n\n")
    f.write("typedef struct { uint32_t id; char kind[3]; char name[25]; } MoveInfo;\n\n")
    for n, chunk in dict_chunks(src, ("Go", "Cs", "Galaxy")).items():
        rows, seen = [], set()
        for m in MOVE.finditer(chunk):
            mid = int(m.group(1), 16)
            name = ascii_name(m.group(2)).strip()[:24]
            if not mid or not name or mid in seen:
                continue
            seen.add(mid)
            rows.append((mid, KIND.get(m.group(4), "??"), name))
        rows.sort()
        up = n.upper()
        f.write(f"#define {up}_MDB_COUNT {len(rows)}\n")
        f.write(f"static const MoveInfo {up}_MDB[{up}_MDB_COUNT] = {{\n")
        for mid, kind, name in rows:
            f.write(f'    {{ 0x{mid:08X}, "{kind}", "{name}" }},\n')
        f.write("};\n\n")
        print("moves", n, len(rows))

# avatars: Cs inherits Go, Galaxy inherits Cs -> cumulative
src = open(BASE + "Avatars/Avatars.cs", encoding="utf-8").read()
AV = re.compile(r'\{0x([0-9A-Fa-f]{8}),\s*new Avatar\("([^"]*)",\s*(\w+)\)')
chunks = dict_chunks(src, ("Go", "Cs", "Galaxy"))
acc = {}
sets = {}
for n in ("Go", "Cs", "Galaxy"):
    for m in AV.finditer(chunks.get(n, "")):
        aid = int(m.group(1), 16)
        name = ascii_name(m.group(2)).strip()[:24]
        if aid and name:
            acc[aid] = (name, 1 if m.group(3) == "true" else 0)
    sets[n] = dict(acc)
with open("3ds/source/avatars_db.h", "w") as f:
    f.write("/* generated by tools/gen_moves.py from Avatars.cs (cumulative dicts) */\n#pragma once\n#include <stdint.h>\n\n")
    f.write("typedef struct { uint32_t id; uint8_t spirit; char name[25]; } AvatarInfo;\n\n")
    for n, d in sets.items():
        rows = sorted(d.items())
        up = n.upper()
        f.write(f"#define {up}_ADB_COUNT {len(rows)}\n")
        f.write(f"static const AvatarInfo {up}_ADB[{up}_ADB_COUNT] = {{\n")
        for aid, (name, sp) in rows:
            f.write(f'    {{ 0x{aid:08X}, {sp}, "{name}" }},\n')
        f.write("};\n\n")
        print("avatars", n, len(rows))
