#!/usr/bin/env python3
"""Generate 3ds/source/players_db.h from the reference editor's player
dictionaries (GO / CS / Galaxy). Names transliterated to ASCII."""

import re
import unicodedata

SRC = "reference/InazumaElevenSaveEditor/InazumaElevenSaveEditor/InazumaEleven/Common/GO/Players/Players.cs"
OUT = "3ds/source/players_db.h"

POS = {"Goalkeeper": "GK", "Defender": "DF", "Midfielder": "MF", "Forward": "FW"}
ELEM = {"Fire": "Fire", "Wind": "Wind", "Wood": "Wood", "Earth": "Erth"}
ENTRY = re.compile(
    r'\{0x([0-9A-Fa-f]{8}),\s*new Player\s*\("([^"]*)",\s*(?:Position\.(\w+)\(\)|null),\s*(?:Element\.(\w+)\(\)|null)'
)


def ascii_name(s):
    s = unicodedata.normalize("NFKD", s)
    return "".join(c for c in s if ord(c) < 128)


FREEDOM = re.compile(r",\s*(\d+)\)\s*\},?\s*$")
STATS = re.compile(r"new List<int>\(\)\s*\{([^}]*)\}")
MOVES = re.compile(r"new List<UInt32>\(\)\s*\{([^}]*)\}")


def parse_dict(chunk):
    rows, seen = [], set()
    for line in chunk.splitlines():
        m = ENTRY.search(line)
        if not m:
            continue
        pid = int(m.group(1), 16)
        name = ascii_name(m.group(2))[:23].replace("\\", "").replace('"', "")
        if pid == 0 or not name or pid in seen:
            continue
        fm = FREEDOM.search(line)
        freedom = int(fm.group(1)) if fm else 0
        sm = STATS.search(line)
        stats = [int(v) for v in sm.group(1).split(",")] if sm else []
        if len(stats) != 10:
            stats = [0] * 10
        stats = [min(max(v, 0), 65535 if i < 2 else 255) for i, v in enumerate(stats)]
        mm = MOVES.search(line)
        moves = [int(v.strip(), 0) for v in mm.group(1).split(",")] if mm else []
        moves = (moves + [0] * 4)[:4]
        seen.add(pid)
        rows.append((pid, POS.get(m.group(3), "??"), ELEM.get(m.group(4), "????"), name, freedom, stats, moves))
    rows.sort()
    return rows


src = open(SRC, encoding="utf-8").read()
marks = {n: src.index(f"{n} = new Dictionary") for n in ("Go", "Cs", "Galaxy")}
bounds = sorted(marks.values()) + [len(src)]
dicts = {}
for n, s in marks.items():
    e = min(b for b in bounds if b > s)
    dicts[n] = parse_dict(src[s:e])

with open(OUT, "w") as f:
    f.write("/* generated by tools/gen_players.py from Players.cs (Go/Cs/Galaxy dicts) */\n")
    f.write("#pragma once\n#include <stdint.h>\n\n")
    f.write("typedef struct { uint32_t id; uint32_t moves[4]; uint16_t freedom, gp, tp; uint8_t st[8]; char pos[3]; char elem[5]; char name[24]; } PlayerInfo;\n\n")
    for n, rows in dicts.items():
        up = n.upper()
        f.write(f"#define {up}_DB_COUNT {len(rows)}\n")
        f.write(f"static const PlayerInfo {up}_DB[{up}_DB_COUNT] = {{\n")
        for pid, pos, elem, name, freedom, st, mv in rows:
            s8 = ", ".join(str(v) for v in st[2:])
            m4 = ", ".join(f"0x{v:08X}" for v in mv)
            f.write(f'    {{ 0x{pid:08X}, {{{m4}}}, {freedom}, {st[0]}, {st[1]}, {{{s8}}}, "{pos}", "{elem}", "{name}" }},\n')
        f.write("};\n\n")
for n, rows in dicts.items():
    print(n, len(rows))
