#!/usr/bin/env python3
"""Generate 3ds/source/unlock_data.h: the UnlockAllData write regions for every
GO-series game/region, parsed from the reference editor's SaveSaveInfo() code."""

import re

BASE = "reference/InazumaElevenSaveEditor/InazumaElevenSaveEditor/InazumaEleven/Games"

STMT = re.compile(
    r"writer\.Seek\((0x[0-9A-Fa-f]+|\d+)\);"
    r"|writer\.Skip\((0x[0-9A-Fa-f]+|\d+)\);"
    r"|writer\.Write\(new byte\[\d+\] \{([^}]*)\}\);"
    r"|writer\.Write\(\(byte\)(0x[0-9A-Fa-f]+|\d+)\);"
)


def parse_regions(chunk):
    pos = None
    regions = []
    for m in STMT.finditer(chunk):
        seek, skip, arr, single = m.groups()
        if seek:
            pos = int(seek, 0)
        elif skip:
            pos += int(skip, 0)
        elif arr is not None:
            data = [int(v.strip(), 0) for v in arr.split(",") if v.strip()]
            regions.append((pos, data))
            pos += len(data)
        elif single:
            regions.append((pos, [int(single, 0)]))
            pos += 1
    return regions


def unlock_block(path):
    src = open(path, encoding="utf-8").read()
    start = src.index("if (SaveInfo.UnlockAllData == true)")
    end = src.index("public void OpenTactics")
    return src[start:end]


def split_jp_eu(block):
    jp_start = block.index("if (helper.IsJP)")
    else_pos = block.index("else", jp_start)
    return block[jp_start:else_pos], block[else_pos:]


sets = {}
sets["galaxy"] = parse_regions(unlock_block(f"{BASE}/IEGOGalaxy/IEGOGalaxy.cs"))
cs = unlock_block(f"{BASE}/IEGOCS/IEGOCS.cs")
sets["cs_jp"], sets["cs_eu"] = map(parse_regions, split_jp_eu(cs))
go = unlock_block(f"{BASE}/IEGO/IEGO.cs")
sets["go_jp"], sets["go_eu"] = map(parse_regions, split_jp_eu(go))

out = [
    "/* generated by tools/gen_unlock.py from the reference editor's",
    " * SaveSaveInfo() UnlockAllData blocks (all GO-series games/regions) */",
    "#pragma once",
    "#include <stdint.h>",
    "",
    "typedef struct { uint32_t offset; uint32_t len; const uint8_t *data; } UnlockRegion;",
    "",
]
for name, regions in sets.items():
    assert regions, name
    for off, data in regions:
        out.append(f"static const uint8_t ul_{name}_{off:05X}[{len(data)}] = {{")
        for j in range(0, len(data), 12):
            out.append("    " + ", ".join(f"0x{v:02X}" for v in data[j:j + 12]) + ",")
        out.append("};")
    out.append(f"static const UnlockRegion UNLOCK_{name.upper()}[] = {{")
    for off, data in regions:
        out.append(f"    {{ 0x{off:05X}, {len(data)}, ul_{name}_{off:05X} }},")
    out.append("};")
    end = max(off + len(data) for off, data in regions)
    out.append(f"#define UNLOCK_{name.upper()}_N {len(regions)}")
    out.append(f"#define UNLOCK_{name.upper()}_END 0x{end:X}")
    out.append("")

open("3ds/source/unlock_data.h", "w").write("\n".join(out) + "\n")
for name, regions in sets.items():
    print(name, [(hex(o), len(d)) for o, d in regions])
