#!/usr/bin/env python3
"""Generate 3ds/source/records_db.h from PlayRecords.cs (Cs / Galaxy dicts)."""

import re
import unicodedata

SRC = "reference/InazumaElevenSaveEditor/InazumaElevenSaveEditor/InazumaEleven/Common/GO/Play Records/PlayRecords.cs"


def ascii_name(s):
    s = unicodedata.normalize("NFKD", s)
    return "".join(c for c in s if ord(c) < 128).replace('"', "")


src = open(SRC, encoding="utf-8").read()
marks = {n: src.index(f"{n} = new Dictionary") for n in ("Cs", "Galaxy") if f"{n} = new Dictionary" in src}
bounds = sorted(marks.values()) + [len(src)]
with open("3ds/source/records_db.h", "w") as f:
    f.write("/* generated by tools/gen_records.py from PlayRecords.cs */\n#pragma once\n#include <stdint.h>\n\n")
    f.write("typedef struct { uint8_t group; char name[28]; } RecordInfo;\n\n")
    for n, s in marks.items():
        chunk = src[s:min(b for b in bounds if b > s)]
        rows = []
        for gm in re.finditer(r"\{(\d+), new List<PlayRecord>\(\)\s*\{(.*?)\}\s*\}", chunk, re.S):
            grp = int(gm.group(1))
            for rm in re.finditer(r'new PlayRecord\("([^"]*)"\)', gm.group(2)):
                rows.append((grp, ascii_name(rm.group(1))[:27]))
        up = n.upper()
        f.write(f"#define {up}_RDB_COUNT {len(rows)}\n")
        f.write(f"static const RecordInfo {up}_RDB[{up}_RDB_COUNT] = {{\n")
        for grp, name in rows:
            f.write(f'    {{ {grp}, "{name}" }},\n')
        f.write("};\n\n")
        print(n, len(rows), "records,", len(set(g for g, _ in rows)), "groups")
